### ISSUE TITLE
Remote Hosting?

### ISSUE THREAD

**Issue by lenichols** [matiastucci/socket-chat-server#3]
What is your advice on how to set there server up on linux remote cloud host. I noticed url - https://socket-chat-server.herokuapp.com:443 how do i execute a url like this that will start my server over a connection?

**Comment by matiastucci** [comment]
You have to clone and start the server in your linux environment:

`$ git clone https://github.com/matiastucci/socket-chat-server.git`
`$ cd socket-chat-server`
`$ npm install`
`$ node server.js`

and then you point the client to: `http://yourDomain.com:443`

**Comment by lenichols** [comment]
but how would i start it on my remote server? or how do i initiate it to start on a device? locally on my desktop i can run node "server.js" but how would i start the server when its loaded onto a device?

**Comment by matiastucci** [comment]
To start the server in your machine you need access to the Linux terminal, and run `node server.js`. It´s the same as local, only that you have to point your client to: `http://yourDomain.com:443`, not `localhost`

**Comment by lenichols** [comment]
so let me make sure i understand this... in order to host my server like yours: https://socket-chat-server.herokuapp.com:443

i need to: 
1. upload the server files (which i did - they are here http://nightvisionapps.com/linkup/server/socket-chat-server/)
2. My port is 7777 - so i need to reference this in my server.js file - http://nightvisionapps.com:7777

and that's it? How come when i navigate to my seerver folder on my remote linux host i get nothing? i feel like im close but still picking thru setup.

**Comment by lenichols** [comment]
sorry if i an idiot... still new to node land but i have your chat system working i just want to host the server on my remote linux box.

**Comment by matiastucci** [comment]
No problem, i'm not an expert either :)

In your `server.js` you don´t had to touch anything.
Let´s forgot about the client for a while and focus on the server. First you need the server running in your Linux machine, and it isn´t. Have you clone the repo and run `node server.js` in the same directory?

**Comment by lenichols** [comment]
locally on my computer yes it runs. when i upload the /socket-chat-server and try to access server.js it does nothing. I have no way to use terminal on my shared host on my remote server. How do It to wrk as yours does... i did try and set up a heroku app service up but i get blank site... i guess i was hoping i could run it from my remote shared host but i guess i cant - https://serene-sands-9250.herokuapp.com/ (does nothing)

**Comment by matiastucci** [comment]
I recommend Heroku.
Read this tutorial: [Deploy a Node app to Heroku](https://scotch.io/tutorials/how-to-deploy-a-node-js-app-to-heroku).

**Comment by lenichols** [comment]
got cha! i will go back thru the tutorial and figure it out. Thanks for two amazing scripts (chat and server).

**Comment by matiastucci** [comment]
You´re welcome. If after reading that tutorial still have questions, feel free to ask.
